<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Data Wrangling Lab**

Estimated time needed: **45** minutes

In this lab, you will perform data wrangling tasks to prepare raw data for analysis. Data wrangling involves cleaning, transforming, and organizing data into a structured format suitable for analysis. This lab focuses on tasks like identifying inconsistencies, encoding categorical variables, and feature transformation.

## Objectives

After completing this lab, you will be able to:

- Identify and remove inconsistent data entries.

- Encode categorical variables for analysis.

- Handle missing values using multiple imputation strategies.

- Apply feature scaling and transformation techniques.

#### Intsall the required libraries

In [1]:
!pip install pandas
!pip install matplotlib

Requirement already satisfied: pandas in /opt/conda/lib/python3.12/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: matplotlib in /opt/conda/lib/python3.12/site-packages (3.11.0)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.25 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (2.4.6)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=9 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.12/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

## Tasks

#### Step 1: Import the necessary module.

### 1. Load the Dataset

<h5>1.1 Import necessary libraries and load the dataset.</h5>

Ensure the dataset is loaded correctly by displaying the first few rows.

In [2]:
# Import necessary libraries
import matplotlib as plt
import pandas as pd

# Load the Stack Overflow survey data
dataset_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n01PQ9pSmiRX6520flujwQ/survey-data.csv"
df = pd.read_csv(dataset_url)

# Display the first few rows
print(df.head())

   ResponseId                      MainBranch                 Age  \
0           1  I am a developer by profession  Under 18 years old
1           2  I am a developer by profession     35-44 years old
2           3  I am a developer by profession     45-54 years old
3           4           I am learning to code     18-24 years old
4           5  I am a developer by profession     18-24 years old

            Employment RemoteWork   Check  \
0  Employed, full-time     Remote  Apples
1  Employed, full-time     Remote  Apples
2  Employed, full-time     Remote  Apples
3   Student, full-time        NaN  Apples
4   Student, full-time        NaN  Apples

                                    CodingActivities  \
0                                              Hobby
1  Hobby;Contribute to open-source projects;Other...
2  Hobby;Contribute to open-source projects;Other...
3                                                NaN
4                                                NaN

                                             EdLevel  \
0                          Primary/elementary school
1       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
2    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
3  Some college/university study without earning ...
4  Secondary school (e.g. American high school, G...

                                           LearnCode  \
0                             Books / Physical media
1  Books / Physical media;Colleague;On the job tr...
2  Books / Physical media;Colleague;On the job tr...
3  Other online resources (e.g., videos, blogs, f...
4  Other online resources (e.g., videos, blogs, f...

                                     LearnCodeOnline  ... JobSatPoints_6  \
0                                                NaN  ...            NaN
1  Technical documentation;Blogs;Books;Written Tu...  ...            0.0
2  Technical documentation;Blogs;Books;Written Tu...  ...            NaN
3  Stack Overflow;How-to videos;Interactive tutorial  ...            NaN
4  Technical documentation;Blogs;Written Tutorial...  ...            NaN

  JobSatPoints_7 JobSatPoints_8 JobSatPoints_9 JobSatPoints_10  \
0            NaN            NaN            NaN             NaN
1            0.0            0.0            0.0             0.0
2            NaN            NaN            NaN             NaN
3            NaN            NaN            NaN             NaN
4            NaN            NaN            NaN             NaN

  JobSatPoints_11           SurveyLength SurveyEase ConvertedCompYearly JobSat
0             NaN                    NaN        NaN                 NaN    NaN
1             0.0                    NaN        NaN                 NaN    NaN
2             NaN  Appropriate in length       Easy                 NaN    NaN
3             NaN               Too long       Easy                 NaN    NaN
4             NaN              Too short       Easy                 NaN    NaN

[5 rows x 114 columns]

#### 2. Explore the Dataset

<h5>2.1 Summarize the dataset by displaying the column data types, counts, and missing values.</h5>

In [3]:
# Write your code here
print(df.dtypes) # Displaying the columns data types
print(f'Counts:{len(df)}') # counts the legnth of the dataframe
df.isnull() # Displaying missing values in the df

ResponseId               int64
MainBranch                 str
Age                        str
Employment                 str
RemoteWork                 str
                        ...
JobSatPoints_11        float64
SurveyLength               str
SurveyEase                 str
ConvertedCompYearly    float64
JobSat                 float64
Length: 114, dtype: object
Counts:65437

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,False,False,False,False,False,False,False,False,False,True,...,True,True,True,True,True,True,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,False,False,True,True
3,False,False,False,False,True,False,True,False,False,False,...,True,True,True,True,True,True,False,False,True,True
4,False,False,False,False,True,False,True,False,False,False,...,True,True,True,True,True,True,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65432,False,False,False,False,False,False,False,False,False,True,...,True,True,True,True,True,True,True,True,True,True
65433,False,False,False,False,False,False,False,True,True,True,...,True,True,True,True,True,True,True,True,True,True
65434,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
65435,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,True,True,True
65436,False,False,False,False,True,False,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

<h5>2.2 Generate basic statistics for numerical columns.</h5>

In [4]:
# Write your code here
df.describe() # Generate basic statistics summary for numerical columns

,ResponseId,CompTotal,WorkExp,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,ConvertedCompYearly,JobSat
count,65437.000000,3.374000e+04,29658.000000,29324.000000,29393.000000,29411.000000,29450.000000,29448.00000,29456.000000,29456.000000,29450.000000,29445.000000,2.343500e+04,29126.000000
mean,32719.000000,2.963841e+145,11.466957,18.581094,7.522140,10.060857,24.343232,22.96522,20.278165,16.169432,10.955713,9.953948,8.615529e+04,6.935041
std,18890.179119,5.444117e+147,9.168709,25.966221,18.422661,21.833836,27.089360,27.01774,26.108110,24.845032,22.906263,21.775652,1.867570e+05,2.088259
min,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000
25%,16360.000000,6.000000e+04,4.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,3.271200e+04,6.000000
50%,32719.000000,1.100000e+05,9.000000,10.000000,0.000000,0.000000,20.000000,15.00000,10.000000,5.000000,0.000000,0.000000,6.500000e+04,7.000000
75%,49078.000000,2.500000e+05,16.000000,22.000000,5.000000,10.000000,30.000000,30.00000,25.000000,20.000000,10.000000,10.000000,1.079715e+05,8.000000
max,65437.000000,1.000000e+150,50.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,1.625660e+07,10.000000

### 3. Identifying and Removing Inconsistencies

<h5>3.1 Identify inconsistent or irrelevant entries in specific columns (e.g., Country).</h5>

In [5]:
# Write your code here
df['EdLevel'].value_counts() # identifying inconsistent entries in EdLevel column

EdLevel
Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          24942
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                       15557
Some college/university study without earning a degree                                 7651
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     5793
Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                         2970
Associate degree (A.A., A.S., etc.)                                                    1793
Primary/elementary school                                                              1146
Something else                                                                          932
Name: count, dtype: int64

<h5>3.2 Standardize entries in columns like Country or EdLevel by mapping inconsistent values to a consistent format.</h5>

In [6]:
## Write your code here
EdLevel_mapping={
'Bachelor’s degree (B.A., B.S., B.Eng., etc.)':'Bachelor',
'Master’s degree (M.A., M.S., M.Eng., MBA, etc.)':'Master',
'Some college/university study without earning a degree' :'Student',
'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)':'Secondary',
'Professional degree (JD, MD, Ph.D, Ed.D, etc.)':'Professional',
'Associate degree (A.A., A.S., etc.)':'Associate',
'Primary/elementary school':'Elementary',
'Something else':'other'
}
# standardize entries in EdLevel column by mapping inconsistent values to consistent format
df['EdLevel']=df['EdLevel'].replace(EdLevel_mapping) 
df['EdLevel']

0        Elementary
1          Bachelor
2            Master
3           Student
4         Secondary
            ...
65432      Bachelor
65433           NaN
65434      Bachelor
65435     Secondary
65436           NaN
Name: EdLevel, Length: 65437, dtype: str

### 4. Encoding Categorical Variables

<h5>4.1 Encode the Employment column using one-hot encoding.</h5>

In [7]:
## Write your code here
df_encoded_emp=pd.get_dummies(df['Employment']) # encodimg column using one-hot encoding
df_encoded_emp

,"Employed, full-time","Employed, full-time;Employed, part-time","Employed, full-time;Independent contractor, freelancer, or self-employed","Employed, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time","Employed, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time;Retired","Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work","Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Employed, part-time","Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time","Employed, full-time;Independent contractor, freelancer, or self-employed;Retired","Employed, full-time;Independent contractor, freelancer, or self-employed;Student, part-time",...,"Student, full-time;Not employed, but looking for work;Not employed, and not looking for work;Student, part-time","Student, full-time;Not employed, but looking for work;Retired","Student, full-time;Not employed, but looking for work;Student, part-time","Student, full-time;Retired","Student, full-time;Student, part-time","Student, full-time;Student, part-time;Employed, part-time","Student, full-time;Student, part-time;Retired","Student, part-time","Student, part-time;Employed, part-time","Student, part-time;Retired"
0,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65432,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
65433,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
65434,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
65435,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
65436,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

### 5. Handling Missing Values

<h5>5.1 Identify columns with the highest number of missing values.</h5>

In [8]:
## Write your code here
df.isnull().sum().idxmax() # finding out the column with the highest number of missing values

'AINextMuch less integrated'

<h5>5.2 Impute missing values in numerical columns (e.g., `ConvertedCompYearly`) with the mean or median.</h5>

In [9]:
## Write your code here
import numpy as np
Mean=df['WorkExp'].mean()
df['WorkExp']=df['WorkExp'].replace(np.nan,Mean) # imputing missing values in the numerical column with the mean

<h5>5.3 Impute missing values in categorical columns (e.g., `RemoteWork`) with the most frequent value.</h5>

In [10]:
## Write your code here
# imputing missing values with the most frequent value
df['RemoteWork']=df['RemoteWork'].replace(np.nan,'Hybrid (some remote, some in-person)')

### 6. Feature Scaling and Transformation

<h5>6.1 Apply Min-Max Scaling to normalize the `ConvertedCompYearly` column.</h5>

In [11]:
## Write your code here
# applying Min-Max scaling to normalize the column
df['ConvertedCompYearly']=(df['ConvertedCompYearly']-df['ConvertedCompYearly'].min())/(df['ConvertedCompYearly'].max()-df['ConvertedCompYearly'].min())

<h5>6.2 Log-transform the ConvertedCompYearly column to reduce skewness.</h5>

In [12]:
## Write your code here
df['ConvertedCompYearly']=np.log1p(df['ConvertedCompYearly']) # reduced column skewness by using log-transform

### 7. Feature Engineering

<h5>7.1 Create a new column `ExperienceLevel` based on the `YearsCodePro` column:</h5>

In [13]:
## Write your code here
# replace the string entries to numeric in YearsCodePro column
df['YearsCodePro']=df['YearsCodePro'].replace({'Less than 1 year':0.5,'More than 50 years':51})

df['YearsCodePro']= df['YearsCodePro'].apply(pd.to_numeric, errors='coerce') #Convert problematic columns to numeric

bins=np.linspace(np.min(df['YearsCodePro']),np.max(df['YearsCodePro']),5) # create bins with bins-width=5

label=['Entry-level','Mid-Level','Senior-Level','Lead'] # create a list, label based on experience level
# Creating a new column 'ExperienceLevel' based on the 'YearsCodePro' column
df['ExperienceLevel']=pd.cut(df['YearsCodePro'],bins,labels=label,include_lowest=True)

df['ExperienceLevel'].head(10)

0             NaN
1       Mid-Level
2    Senior-Level
3             NaN
4             NaN
5             NaN
6     Entry-level
7             NaN
8             NaN
9     Entry-level
Name: ExperienceLevel, dtype: category
Categories (4, str): ['Entry-level' < 'Mid-Level' < 'Senior-Level' < 'Lead']

### Summary

In this lab, you:

- Explored the dataset to identify inconsistencies and missing values.

- Encoded categorical variables for analysis.

- Handled missing values using imputation techniques.

- Normalized and transformed numerical data to prepare it for analysis.

- Engineered a new feature to enhance data interpretation.

Copyright © IBM Corporation. All rights reserved.